[workspace]
[package]
version = "0.1.0"
name = "sha2-precompile"
edition = "2021"

[dependencies]
# zkm-runtime = { git = "https://github.com/zkMIPS/zkm", package = "zkm-runtime" }
zkm-runtime = { path = "../../../../runtime/entrypoint" }
sha2 = { version = "0.10.8", default-features = false }
